version: 0.0
env:
  variables:
    APP_NAME: "hello"
    IMAGE_TAG: ""
    IMAGE: ""

os: linux
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
      runas: root
  LoginGithub:
    - location: ascripts/login_github.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: root
