version: 0.0
env:
  variables:
    APP_NAME: ""
    IMAGE: ""

os: linux
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh $APP_NAME
      timeout: 300
      runas: root
  LoginGithub:
    - location: ascripts/login_github.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh $APP_NAME $IMAGE
      timeout: 300
      runas: root
