version: 0.0
env:
  variables:
    APP_NAME: "hello"
    IMAGE_TAG: ""
    IMAGE: ""

os: linux
files:
  - source: /aws
    destination: /usr/local/codedeployresources
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 300
      runas: root