version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh 
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: root
