name: deploy Image for prod 

on:
  workflow_dispatch:
    inputs:
      admin_approval:
        description: 'Require admin approval'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run workflow from main repository
        uses: ./workflows/hello.yml