name: Build Image for test 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hello
on:
  push:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Packages
        if: ${{ github.ref_type == 'branch' }}
        run: echo "${{ secrets.SECRETS_GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      
      - name: Get Short SHA
        if: ${{ github.ref_type == 'branch' }}
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "Short SHA: $SHORT_SHA"
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Build images
        if: ${{ github.ref_type == 'branch' }}
        run: make build ARGS="ghcr.io/${{ github.repository }}/" IMAGE_TAG="${{ env.SHORT_SHA }}" IMAGE_NAME=${{ env.IMAGE_NAME }}

      - name: Push images to repository
        if: ${{ github.ref_type == 'branch' }}
        run: make push ARGS="ghcr.io/${{ github.repository }}/" IMAGE_TAG="${{ env.SHORT_SHA }}" IMAGE_NAME=${{ env.IMAGE_NAME }}

  deploy_test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Get Short SHA
        run: echo "${GITHUB_SHA:0:7}" > short_sha.txt
        
      - name: Deploy Test
        uses: appleboy/ssh-action@v1.0.3
        env:
          GITHUB_ACTOR: $GITHUB_ACTOR
          SECRETS_GITHUB_TOKEN: ${{ secrets.SECRETS_GITHUB_TOKEN }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ env.SHORT_SHA }}
          repository: ${{ github.repository }}
        with:
          host: ${{ secrets.REMOTE_HOST_TEST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY_TEST }}
          port: 22
          envs: GITHUB_ACTOR,SECRETS_GITHUB_TOKEN,IMAGE_NAME,IMAGE_TAG,repository
          script: |
            echo "$GITHUB_ACTOR $repository $GITHUB_ACTOR"