on: [push]

env:
  # IMAGE_NAME 用于 程序名
  GITHUB_REPO: ghcr.io/${{ github.repository }}
  AWS_REGISTRY: 580167004110.dkr.ecr.ap-southeast-1.amazonaws.com
  SECRETS_GITHUB_TOKEN: ${{ secrets.SECRETS_GITHUB_TOKEN }}
  AWS_ACCOUNT: 580167004110

jobs:
  test-public-repo:

    runs-on: ubuntu-latest

    name: Get the sha from public repo

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2

    - name: check repo node
      run: |
        pwd
        ls ./

    - name: checkout action repo
      uses: actions/checkout@v2
      with: 
        repository: davema-clan/github-action-tmp
        token: ${{ secrets.SECRETS_GITHUB_TOKEN }}

    - name: check repo
      run: |
        pwd
        ls ./

    - name: Action Test
      id: test
      uses: ./github-action-tmp
